# Defines stages which are to be executed
stages:
  - syntax
  - test

#
### Stage syntax
#

syntax:lint:
  stage: syntax
  image: bobey/docker-gitlab-ci-runner-php7
  allow_failure: false
  only:
    - schedules
    - web
    - merge_requests

  script:
    - composer require overtrue/phplint
    - echo "Syntax checking PHP files"
    - echo "For more information http://www.icosaedro.it/phplint/"
    - vendor/bin/phplint


test:install:
  stage: test
  image: jerob/docker-ispconfig
  only:
    - schedules
    - web
    - merge_requests
  script:
    - $CI_PROJECT_DIR/helper_scripts/test_install_docker.sh
    - apt-get update
    - apt-get --yes install curl
    - curl --insecure https://127.0.0.1:8080/login/
    - ps xaf
