# Defines stages which are to be executed
stages:
  - syntax

#
### Stage syntax
#

syntax:lint:
  stage: syntax
  image: bobey/docker-gitlab-ci-runner-php7
  allow_failure: false
  only:
    - schedules
    - web
    - master@ispconfig/ispconfig3
    - stable-3.1@ispconfig/ispconfig3

  script:
    - composer require overtrue/phplint
    - echo "Syntax checking PHP files"
    - echo "For more information http://www.icosaedro.it/phplint/"
    - vendor/bin/phplint
